name: CI/CD Pipeline

on:
  push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: make install
        
      - name: Format the code
        run: make format

      - name: Lint the code
        run: make lint

      - name: Run tests on the main Python file
        run: make test
      
      - name: Generate reports on the run
        run: make generate